image: alpine
before_script:
  - eval `ssh-agent -s` && ssh-add
  - ./bootstrap.sh
  - bin/buildout -N
  - bin/buildout -N remotes:branch=$CI_COMMIT_REF_NAME
  - bin/develop up --force
tests:
  script:
    - bin/py.test ./openprocurement/planning/api/tests --cov=openprocurement/planning/api

